// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjaJD0EAPlnQbIEfrSb9_aOw0btiWW7m8',
    appId: '1:322399272127:web:137c41031e1715a1ff1a0a',
    messagingSenderId: '322399272127',
    projectId: 'splitify-c58bd',
    authDomain: 'splitify-c58bd.firebaseapp.com',
    storageBucket: 'splitify-c58bd.firebasestorage.app',
    measurementId: 'G-2JDWMR65LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq3KDFqgEBN6xVbvYf1QGiAkulW-IUSNI',
    appId: '1:322399272127:android:901d4bf49084e1fdff1a0a',
    messagingSenderId: '322399272127',
    projectId: 'splitify-c58bd',
    storageBucket: 'splitify-c58bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD71nhwcmc9Nj34-zdzkuF2HBzwkoqk_do',
    appId: '1:322399272127:ios:c150d2c552c2ddeeff1a0a',
    messagingSenderId: '322399272127',
    projectId: 'splitify-c58bd',
    storageBucket: 'splitify-c58bd.firebasestorage.app',
    iosBundleId: 'com.example.splitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD71nhwcmc9Nj34-zdzkuF2HBzwkoqk_do',
    appId: '1:322399272127:ios:c150d2c552c2ddeeff1a0a',
    messagingSenderId: '322399272127',
    projectId: 'splitify-c58bd',
    storageBucket: 'splitify-c58bd.firebasestorage.app',
    iosBundleId: 'com.example.splitify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjaJD0EAPlnQbIEfrSb9_aOw0btiWW7m8',
    appId: '1:322399272127:web:ae5b10612a142c46ff1a0a',
    messagingSenderId: '322399272127',
    projectId: 'splitify-c58bd',
    authDomain: 'splitify-c58bd.firebaseapp.com',
    storageBucket: 'splitify-c58bd.firebasestorage.app',
    measurementId: 'G-S78T027NYH',
  );
}
